name: Trigger auto deployment for demo-ethereal-nexus

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demo-ethereal-nexus-AutoDeployTrigger-f40fd3d8-f268-4d2f-9a24-ebb8f4096973.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.DEMOETHEREALNEXUS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: web/dashboard/Dockerfile
          containerAppName: demo-ethereal-nexus
          resourceGroup: RG-Ethereal-Nexus
          registryUrl: registry.hub.docker.com
          targetPort: 3000 --registry-server registry.hub.docker.com
          registryUsername: ${{ secrets.DOCKER_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PASSWORD }}
          imageToBuild: registry.hub.docker.com/docker19diconium/remote-components:${{ github.sha }}



     

