name: Trigger auto deployment for demo-ethereal-nexus

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demo-ethereal-nexus-AutoDeployTrigger-7615f6cd-fea1-4cd6-ada2-da4e6b37a1ec.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEMOETHEREALNEXUS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEMOETHEREALNEXUS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEMOETHEREALNEXUS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/web/dashboard
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: etherealnexus.azurecr.io
          registryUsername: ${{ secrets.DEMOETHEREALNEXUS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOETHEREALNEXUS_REGISTRY_PASSWORD }}
          containerAppName: demo-ethereal-nexus
          resourceGroup: RG-Ethereal-Nexus
          imageToBuild: etherealnexus.azurecr.io/demo-ethereal-nexus:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


